# ... (steps এর আগে)

steps:
- name: Checkout code
  uses: actions/checkout@v3

- name: Setup SSH
  # ... (আগের মতোই)

- name: Deploy to Server
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
      cd /var/www/academy.banglachatbot.com
      git pull origin main
      
      # .env ফাইল তৈরি করা (যদি না থাকে)
      if [ ! -f .env ]; then
        cp .env.example .env
        /usr/bin/php8.3 artisan key:generate
        echo ".env file created and key generated."
      fi
      
      # ... (বাকি কমান্ডগুলো)
    EOF