# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI/CD 

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: [self-hosted, production]

    steps:
      # Step 1: Code checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup runner or install dependencies (যদি প্রয়োজন হয়)
      - name: Setup Runner
        run: |
          # যেকোনো অতিরিক্ত dependency ইন্সটল করতে পারেন
          echo "Setting up necessary environment"

      # Step 3: Files copy or move
      - name: Copy files to another directory
        run: |
          # প্রথমে নিশ্চিত হয়ে নিন যে /var/www/academy.banglachatbot.com ফোল্ডারটি আছে
          echo "Copying files from the runner's working directory to another directory"
          
          # Move or copy the files
          mkdir -p /var/www/academy.banglachatbot.com  # যদি folder না থাকে
          cp -fr /home/whmroot/actions-runner/_work/bcbacademy/bcbacademy/* /var/www/academy.banglachatbot.com/

      # Step 4: Verify the files are copied
      - name: Verify files in the target directory
        run: |
          ls /var/www/academy.banglachatbot.com/
