name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Host to Known Hosts
      run: ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        echo ">>> Deploying to ${{ secrets.HOST }} as user ${{ secrets.USERNAME }} on port ${{ secrets.PORT }}"
        ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          echo ">>> Connected to server. Changing directory..."
          cd /home/academy.banglachatbot.com/public_html
          
          echo ">>> Pulling latest code from main branch..."
          git pull origin main
          
          echo ">>> Installing Composer dependencies..."
          /usr/local/lsws/lsphp83/bin/php /usr/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          
          echo ">>> Running database migrations..."
          /usr/local/lsws/lsphp83/bin/php artisan migrate --force
          
          echo ">>> Caching configuration..."
          /usr/local/lsws/lsphp83/bin/php artisan config:cache
          /usr/local/lsws/lsphp83/bin/php artisan route:cache
          /usr/local/lsws/lsphp83/bin/php artisan view:cache
          
          echo ">>> Deployment successful!"
        EOF